### ISSUE TITLE
Some files can't be downloaded

### ISSUE THREAD

**Issue by arabensis** [avluis/Hentoid#430] opened 2019-12-12 15:09 UTC
Hentoid Version: 1.10.1

Device/Android Version: Galaxy Note 10 5G(SM-N971N) / 9

Issue details / Repro steps: When downloading a file from Hitomi, this content cannot be downloaded.

Stack trace / LogCat: Networking error

paste stack trace and/or log here
Error log : begin
Hentoid ver: 1.10.1 (168)
Error log for Ganbaru Onnanoko [1532454@hitomi] : 18 errors
2019-12-13T00:07:09.799 01 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/1.jpg.webp
2019-12-13T00:07:09.804 02 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/2.jpg.webp
2019-12-13T00:07:10.008 04 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/4.jpg.webp
2019-12-13T00:07:10.022 03 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/3.jpg.webp
2019-12-13T00:07:10.036 05 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/5.jpg.webp
2019-12-13T00:07:10.226 06 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/6.jpg.webp
2019-12-13T00:07:10.247 07 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/7.jpg.webp
2019-12-13T00:07:10.267 08 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/8.jpg.webp
2019-12-13T00:07:10.444 09 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/9.jpg.webp
2019-12-13T00:07:10.461 10 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/10.jpg.webp
2019-12-13T00:07:10.47 11 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/11.jpg.webp
2019-12-13T00:07:10.617 12 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/12.jpg.webp
2019-12-13T00:07:10.799 13 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/13.jpg.webp
2019-12-13T00:07:11.301 14 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/14.jpg.webp
2019-12-13T00:07:11.866 15 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/15.jpg.webp
2019-12-13T00:07:12.37 16 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/16.jpg.webp
2019-12-13T00:07:12.879 17 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/17.jpg.webp
2019-12-13T00:07:13.392 18 - [Networking] : Server error; HTTP statusCode=404; message=null @ https://ba.hitomi.la/webp/1532454/18.jpg.webp
Error log : end

**Comment by RobbWatershed** [comment] 2019-12-12 16:04
Thanks for the report. I'll close the issue as it is a duplicate of #428.

**Closed by RobbWatershed** 2019-12-12 16:04 UTC

**Comment by arabensis** [comment] 2019-12-12 16:25
> Thanks for the report. I'll close the issue as it is a duplicate of #428.

Good job. Thank you for your service. I hope you will take action. I don't mind if it was a translator.
