### ISSUE TITLE
Feature Request: Add options for downloading as .cb* archives

### ISSUE THREAD

**Issue by LiftedStarfish** [avluis/Hentoid#847] opened 2021-10-23 13:39 UTC
Feature Request: I have seen people request that you allow for the importing of .cbz, .cbr, etc. file formats for comics. I've seen that cbz and cbr have been implemented, as well as their respective archive bases.

I'd like to request that we extend this functionality, allowing users the ability tell the application to create an archive when it's downloaded. I would argue that this should be the default functionality, but I can imagine it breaking a lot of people's libraries when they get the update, so I think that's asking a bit much.

Issue #218 actually mentioned that doing such a thing would be helpful with addressing their issue, regarding images being user readable, causing them to be visible from the gallery, where they might not/probably don't wan't them, and I'd argue that it's a very simple solution to that problem (unless I'm drastically underestimating how easy it is to make a comic archive on download.)

In addition, I'd also like to request that compatibility with the .acbf (advanced comic book format) be implemented. ACBF as a standard has not had wide adoption yet, unfortunately due in part to the lack of updates for the specification and applications made by the original devs (the editor that they made was still using GTK2). However I'm currently working on updating some stuff in the editor myself, and I definitely think that the format specification could use some changes, and given that it seems like the original devs have all but abandoned it, I might as well see what I can do with it.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment] 2021-11-21 12:50
First of all, sorry for the delay. I agree with your suggestion of separating that issue into 3 different issues 👍 

> Improve existing archive feature to allow for users to specify location and name of exported archive

I've just created #872 


> Import and read .cb* archive

CBR, CBZ and CB7 are already supported. Is there something missing ?


> Download as comic archive (.cbz)

I've just created #873


I hope we've covered the whole matter 😉   If so, I'd suggest to close the present issue (#847) which has been linked to the two others above as reference.

**Comment by LiftedStarfish** [comment] 2021-12-13 21:00
Sorry for the delay, but I've just got one more issue that I really want to reiterate.

> CBR, CBZ and CB7 are already supported. Is there something missing ?

Currently, unless there's something wrong with my device, I cannot _read_ cb* archives using Hentoid, I can only create them. I can select an un-archived comic in the library view, and then tap on the 'archive' button, but doing so has a few issues.
- The comic is archived into the system Downloads directory, not the application's download directory.
- It's a .zip archive, not .cbz (although the distinction isn't that important because of the next item.)
- Whether it's a .cbz or a .zip, Hentoid (or Hendroid, a fork with Google Play Services removed) cannot open the archive. It shows up in the library/gallery, but the thumbnail is missing, and when I try to read the file, none of the images will load, and it displays an 'image not found' message. It's able to read the metadata, but not the images themselves.

**Comment by RobbWatershed** [comment] 2021-12-14 07:59
> The comic is archived into the system Downloads directory, not the application's download directory.

That will be handled in #872

> It's a .zip archive, not .cbz (although the distinction isn't that important because of the next item.)

That will be handled in #873 

> Whether it's a .cbz or a .zip, Hentoid (or Hendroid, a fork with Google Play Services removed) cannot open the archive

That is not normal at all and should already work. Are you certain you imported it using the external library feature (Import > Storage > External library) ? Is there something wrong in the import log ? Are these files protected by a password ?

**Comment by LiftedStarfish** [comment] 2021-12-17 05:06
No, I had not thought to try that, but I'll do it now after I type this real quick. I actually move the archive into the Hentoid/hendroid (they're both installed but use the same directory) main library/downloads directory. I've tried the main directory, and the specific nHentai directory (I only download from there), and I cannot read from either.

**Comment by RobbWatershed** [comment] 2021-12-17 10:22
Thanks for your feedback, as always ! 😄 

> While this is partly my responsibility for not using the proper methodology, in my defence, it had never been indicated to me that I would need to import archived comics as if they were from an external library.

We do have a non-existent user manual, which does not makes things easy if you're looking for a very specific feature, granted.

> I think it's also an issue that the you need to import it for every new comic that's archived (at least, that seems to be the case).
>  it'd be nice if there were a setting to tell the program that I want it to scan my libraries automatically for new content so that, it there is any,

There's no auto-scan feature yet, but that might be technically feasible. I've opened #880 for that

> I am also a bit confused as to why every archive imported needs to extract the meta info file. Unless I'm mistaken (which I'm very well may be), Librera does not need to extract the image and store it outside of the epub (which is just a zip file) in order to display it's meta data.

Do you mean "why does Hentoid create a `json` metadata file near every single archive ?". That's by design, as the app needs something to remember per-book stats (e.g. completion, number of times you opened it, last page you were on, custom title...) independently from the app's internal database that gets deleted when you uninstall the app.

I hope I've answered all your questions~~

**Comment by RobbWatershed** [comment] 2023-05-09 11:50
All clarified questions have been files as separate issues.

I'm closing that issue as the conversation is over.

**Closed by RobbWatershed** 2023-05-09 11:50 UTC
Labels: enhancement
