### ISSUE TITLE
Error in my hentoid-by hitomi download

### ISSUE THREAD

**Issue by dpqldyd22** [avluis/Hentoid#278] opened 2019-04-09 15:29 UTC
Error in my hentoid-by hitomi download.

Hentoid Version is 1.6.8(hot fixed)

Device is LG G2/Android Version is 4.4

If I download a file from hentoid-hitomi, the download fails with an unknown error. Although continued re-download, download errors will not be resolved.
I tried to re-download it by changing the network, but the download is failed.

This is part of the error code log.
001 - [Networking] : Auth failure; HTTPstatusCode=403; message=null@ https://ba.hitomi.la/galleries/1395427/1.png
002 - [Networking] : Auth failure; HTTPstatusCode=403; message=null@ https://ba.hitomi.la/galleries/1395427/2.png

**Comment by RobbWatershed** [comment] 2019-04-09 17:15
Thanks for the report. We're working on it at the moment. A hotfix should be published soon.

**Comment by herdidi47** [comment] 2019-04-09 22:40
hi. your issue should already be fixed in latest update that you can download [here](https://github.com/avluis/Hentoid/releases/download/v1.6.9/hentoid16989.apk)

**Comment by RobbWatershed** [comment] 2019-04-10 12:12
The issue is considered closed.

**Closed by RobbWatershed** 2019-04-10 12:12 UTC
