### ISSUE TITLE
problem with merging books

### ISSUE THREAD

**Issue by a7mad1996** [avluis/Hentoid#1171] opened 2024-07-13 23:55 UTC
When I combine books, I transfer images to one very large book. This is because at the beginning of the transfer, the transfer is fast and then begins slowed  gradually. This is what I noticed in all versions except for the 1.18.0 v , in which the average transfer speed is maintained, and this saves four times the time. Note that I have tried all ver.  On various devices, they all have the same problem, so there is a problem transferring after this version. Please solve it

**Comment by RobbWatershed** [comment] 2024-09-08 14:26
Let me get this straight : you're using the "merge" feature to combine books, and noticed that all Hentoid releases process your pages too slowly, _except_ v1.18.0 ?

**Comment by a7mad1996** [comment] 2024-09-26 02:51
When I use it all over after 1.18.0 the process will be very slow but only version 1.18 and down the process x10 more speed if I compare in another, note: I try more one mobile and the results it is the same

**Comment by RobbWatershed** [comment] 2024-09-26 11:00
That's odd : we didn't change anything merge or file-related between v1.18.0 and v1.18.1, even among libraries.

Here's [the diff](https://github.com/avluis/Hentoid/compare/v1.18.0...v1.18.1)

Could you double-check the version number where it all begins?

**Comment by a7mad1996** [comment] 2024-09-27 06:24
https://github.com/user-attachments/assets/e4d3085d-1f96-4be8-93e1-45926b62b314

`

https://github.com/user-attachments/assets/6dde2637-b7df-41a9-ad4e-33c7433170a8

`This is a comparison between the first one merged 1600 photos and took 1:45 min and the last version 1.19.12  merged 1000 photos in time 4:41 min ,this mean the old version 3 time speed from last ver,and this vedio provide what is sayed

**Comment by RobbWatershed** [comment] 2024-09-30 06:33
Maybe I didn't make my previous comment clear enough : I don't accuse you of lying or anything - I'd like you to confirm the first app version number where this change of behaviour can be observed. 

> When I use it all over after 1.18.0 the process will be very slow but only version 1.18 and down the process x10 more speed 

I think you wrote it all starts at v1.18.1, but no part of the code can explain that, that's why I 'm asking you to confirm the problem :
- Doesn't exist on v1.18.0 and below
- Exist on v1.18.1 and higher

I'll start my investigations once we get the version numbers right.

Thanks in advance~

**Comment by a7mad1996** [comment] 2024-10-05 10:53
I apologize for the delay in responding. Exactly right, just like you mentioned before. The problem doesn't exist on v1.18.0 and below, but the problem exists on v1.18.1 and higher, I tried multiple devices and the issue had the same results 
Thank you for responding.

**Comment by RobbWatershed** [comment] 2024-10-29 20:45
Did some performance tests today by merging the same books (1009+750 pages) with different versions of the app.

v1.18.0 -> 4:12
v1.18.1 -> 4:06
v1.18.3 -> 4:02
v1.18.4 -> 6:49
v1.18.5 -> 6:42
v1.19.0 -> 6:40
v1.20.0 -> 7:53

Looks like there's an issue indeed, but that issue happened somewhere between v1.18.3 and v1.18.4.

I'll take a closer look to find the cause.

**Comment by RobbWatershed** [comment] 2024-10-29 21:03
Problem comes from that fix, which comes with good intentions but isn't optimized at all when called from a loop : https://github.com/avluis/Hentoid/commit/05a108262ae4a06b924de9ddebfc98982f9f48d0

That means there's a solution to that 😉

**Comment by RobbWatershed** [comment] 2024-10-31 08:18
Problem has been solved : f9d4f56378ace511d1ed6bea5913443f15163bd0

Next release should go back to performances similar to v1.18.0

**Comment by RobbWatershed** [comment] 2024-10-31 20:30
Fixed by today's v1.20.1

**Closed by RobbWatershed** 2024-10-31 20:30 UTC
Labels: bug, awaiting release
