### ISSUE TITLE
Stabilize the app

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#781] opened 2021-04-03 14:38 UTC
The app lags whenever you delete lots of titles all at once and not all are deleted, because it crashes. Also both delete buttons don't work properly as they also lag when you press on them you need to press more than once to delete something. And when you delete using swipe action sometimes the title stays on the background even though it was deleted. Please try to stabilize the app with the next update on these problems.

**Comment by RobbWatershed** [comment] 2021-04-03 14:47
I can't guarantee that will be done on the next update, but it will be eventually taken care of

**Comment by Jinotu** [comment] 2021-04-03 15:29
> I can't guarantee that will be done on the next update, but it will be eventually taken care of

Here is how it looks.
![Screenshot_20210403-111919_Hentoid](https://user-images.githubusercontent.com/77118844/113482855-7da1c800-946e-11eb-9396-dc6e19a059fa.png)
And this thing stays on background while I scroll down.
And this is how it looks between the titles.
![Screenshot_20210403-112655_Hentoid](https://user-images.githubusercontent.com/77118844/113483072-a1b1d900-946f-11eb-9b5b-afc1cf283c93.png)
This is so you get better visuals on what you should work on.

**Comment by RobbWatershed** [comment] 2021-04-04 09:08
this one has been reported a couple times but I haven't been able to reproduce it yet :/

**Comment by RobbWatershed** [comment] 2021-05-23 06:47
Small update following today's release (v1.14.5)

> The app lags whenever you delete lots of titles all at once and not all are deleted, 
> Also both delete buttons don't work properly as they also lag 
The app doesn't lag anymore when starting to mass-delete

> because it crashes. 
Mass-deletion-related crash will be fixed in v1.15; see #692

> Also both delete buttons don't work properly as you need to press more than once to delete something. 
I have no idea about the top bar button. Regarding the "swipe to delete" button, the issue is still there (though kinda random) and will be taken care of in future releases

> And when you delete using swipe action sometimes the title stays on the background even though it was deleted. 
Recent changes may have improved that. Could you give us feedback using today's update ?

**Comment by RobbWatershed** [comment] 2021-06-03 20:01
Small update following today's release (v1.14.7)

> Also both delete buttons don't work properly as you need to press more than once to delete something.

I have no idea about the top bar button. Regarding the "swipe to delete" button, the issue has been fixed.

Only remaining issue is #692

**Comment by RobbWatershed** [comment] 2021-07-07 19:43
Last issue has been fixed for the app's next release

**Closed by RobbWatershed** 2021-07-07 19:43 UTC
Labels: bug
