### ISSUE TITLE
Nhentai website doesn't open

### ISSUE THREAD

**Issue by Dreamx1234** [avluis/Hentoid#1091] opened 2023-08-19 12:56 UTC
-The website keeps reloading back to verify if u are a human.

**Hentoid Version**:

-The latest from 2 days ago post

**Device/Android Version**:

-Realme 7i

**Issue details / Repro steps**:

-Nhentai website doesn't open for me just keeps reloading back to verifying if im a human

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
-I don't get errors

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment] 2023-08-20 08:07
You may try to clear cookies and disable "augmented browser" in the settings.

If that doesn't work, just wait it out. We haven't found any solution to circumvent that kind of Cloudflare blocking yet.

**Comment by Dreamx1234** [comment] 2023-08-20 11:31
Still doesn't work but im willing to wait

**Comment by RobbWatershed** [comment] 2023-08-23 07:08
We've had a user report today saying that the Clouflare page works again with the app.

Could you confirm (after clearing cookies and disabling augmented browser)?

**Comment by Dreamx1234** [comment] 2023-08-23 09:20
I think the problem is in my end i don't know why cloudfare is rejecting my connection but it works if i use chrome browser it wouldn't open with any other browser

**Comment by boyboy-del** [comment] 2023-09-07 13:46
I have the same issue, I have tried clearing cookies and disabling augmented browser, clearing app data, and using a new tablet. I tested it on a pixel 7 pro, that works, and a galaxy tab 3 (doesn't work) and a new pixel tablet (doesn't work). When attempting to access nHentai via chrome and Firefox, it works as long as the browser doesn't force desktop mode.

**Comment by RobbWatershed** [comment] 2023-09-07 16:04
Thanks for that new detailed feedback. From what our users tell us on Discord, this issue _seems_ to be regional. There are still many people who can log in through the app. However, we are still unable to diagnose what's going wrong.

Last but not least, I can confirm Hentoid always uses mobile (i.e. non-desktop) mode when browsing nhentai, as Cloudflare is very sensitive to `user-agent` variations.

Could you tell me which versions of Android are installed on these three devices?

**Comment by boyboy-del** [comment] 2023-09-07 16:24
Pixel 7 pro - Android 13
Galaxy Tab S3 - Android 9
Pixel Tablet - Android 13

All up to date with current security patches

**Comment by boyboy-del** [comment] 2023-09-07 16:43
When connecting through a commercial VPN through the UK (I am located in NA), on the Tab S3 nHentai works.

**Comment by Zkeikk** [comment] 2023-10-12 04:58
I'm getting this same issue. I had updated from 1.8.0 to 1.8.6 and the issues started. I then got a new tablet and fresh install of 1.8.6 and same issue. I then factory reset and did a fresh install of 1.8.0 and same issue. Now I'm just using 1.8.6. Tab s9 ultra android 13, latest security patches and update. Previous deuce was a tab s8+. I had also tried using a vpn and disabled augmented browser.

**Comment by Kiki88x** [comment] 2023-10-14 17:51
I want to request for editing User Agent String to this

Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.196 Mobile Safari/537.36

On this time being It works on every cloudflare. Or i hope you can make option on the apps to custom agent string. Please...

**Comment by RobbWatershed** [comment] 2023-10-15 14:06
@Kiki88x don't post your request on multiple issues at once. It already has a dedicated issue you created yourself : #1103

**Comment by Kiki88x** [comment] 2023-10-15 14:12
> @Kiki88x don't post your request on multiple issues at once. It already has a dedicated issue you created yourself : #1103

Im really sorry, i forgot to delete it. 😅😅

**Comment by boyboy-del** [comment] 2023-10-16 01:55
Cloudflare will allow access if the display size is increased in android settings. I've tested this on Galaxy Tab S3 and Pixel Tablet. Sometimes after the display size is lowered back to original Clouldflare will still allow access.

**Comment by RobbWatershed** [comment] 2024-01-21 16:18
Closed as Cloudflare seems to be less aggressive now. It's been weeks since we last had any report about NH on Discord.

**Closed by RobbWatershed** 2024-01-21 16:18 UTC
Labels: bug
