### ISSUE TITLE
Filtering by pages

### ISSUE THREAD

**Issue by Azoz5643** [avluis/Hentoid#301] opened 2019-05-26 00:26 UTC
**Hentoid Version**:Latest

**Device/Android Version**: 9

**Issue details / Repro steps**: Can you filter the downloaded doujins by pages as More/Less ? Sometimes I don't have much time and want to read something like less than 30 pages but searching for them makes a hard time. Thanks

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment] 2019-05-26 05:47
Duplicate of #222

**Closed by RobbWatershed** 2019-05-26 05:47 UTC
