### ISSUE TITLE
Add New source...

### ISSUE THREAD

**Issue by Kiki88x** [avluis/Hentoid#1057] opened 2023-03-28 08:01 UTC
**Hentoid Version**: 1.17.7

**Device/Android Version**: sony experia xz1

**Issue details / Repro steps**: new source 

 https://ksk.moe/

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment] 2023-03-28 16:47
Duplicate of #998

**Closed by RobbWatershed** 2023-03-28 16:47 UTC
Labels: duplicate
