### ISSUE TITLE
Option to change app incon

### ISSUE THREAD

**Issue by Budiawan69** [avluis/Hentoid#909] opened 2022-02-05 02:52 UTC
**Hentoid Version**:1.5.20

**Device/Android Version**:6.1

**Issue details / Repro steps**:add option to change app after installed

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

Just a idea to keep your comic secretly

**Comment by RobbWatershed** [comment] 2022-02-05 11:30
Duplicate of #591

**Closed by RobbWatershed** 2022-02-05 11:30 UTC
Labels: duplicate
