### ISSUE TITLE
downloads from hitomi are failing

### ISSUE THREAD

**Issue by Saturday9937** [avluis/Hentoid#179] opened 2018-09-15 01:26 UTC
I'm using app version 1.3.10.

When I tried to download, all downloads are rapidly ended in queue and all files had error.
(in 'Downloads' page, all titles have 'red !' sign and says "Try downloading again? /Total images in download: 25 / **Images without error: 0** / Images with error:25", for example)

I deleted cache, and nothing changed.
I deleted data and reimported my downloaded files, and nothing changed.
I deleted app and reinstalled, and nothing changed.

All this errors happened since yesterday. Before that day, all downloads are completed without errors. (or completed with a few amounts of errors first time, but when I tried downloading it again and again, finally completed without errors)

**Comment by avluis** [comment] 2018-09-15 15:12
Can you be more detailed;
What source are you downloading from? (nhentai, tsumino, etc)
Did you download using the same connection as the day before?
Deleting cache or data does nothing if downloads are failing, so no need to retry that.
Can you check how much free space you have and post that in your reply.

**Comment by neosyusaki** [comment] 2018-09-16 17:54
Same issue here, they started show error download. I'm download from hitomi and my connection is the same everytime

**Comment by Saturday9937** [comment] 2018-09-17 05:59
Sorry I forgot to notice downloading source.

I used hitomi to download, like my friend neosyusaki did.

And of course I used same connection(wi-fi).

Also, I got free memory spaces enough to download all my lists in queue.

**Comment by avluis** [comment] 2018-09-17 12:04
So both Hitomi.
Do you guys/gals mind checking the other sources when this issue reoccurs.
I'm thinking this may just be something that broke because of Hitomi (meaning, website issues).

**Comment by neosyusaki** [comment] 2018-09-17 13:46
Just try Hcafe and it work! So it must be hitomi site then. Kinda sad

**Comment by ljy990415** [comment] 2018-09-23 15:45
I've been trying to download from hitomi, but none of the files succeed to download 
:(
I also tried downloading from nhentai, and it worked.
So it seems to have problem while downloading from hitomi.
i'm using version 1.3.10 and I had enough memorry space for downloading files

**Comment by wightwulf1944** [comment] 2018-09-25 14:34
Hitomi's new https protocols aren't working with okhttp. We still don't know what's the cause is but it works with regular HttpUrlConnection.

We're still discussing how to approach this issue

**Comment by RobbWatershed** [comment] 2018-10-02 11:14
The issue has been solved and is currently under community testing (see the announcements desction of the official Discord channel).

The fix will be released in 1-2 weeks if testing proves successful.

**Comment by RobbWatershed** [comment] 2018-10-24 18:14
Fixed in today's release (1.5.2)

**Closed by RobbWatershed** 2018-10-24 18:14 UTC
