### ISSUE TITLE
two pages on one screen

### ISSUE THREAD

**Issue by JumboSK** [avluis/Hentoid#1143] opened 2024-02-08 15:33 UTC
Please can you add support for like fold devices / 2 screens devices?

I had Microsoft surface duo with 2 screens (something like fold device) and i want to use it as book, like 2 pages on screen bacouse when its open i have big screen. 
I try gallery mode but its not on whole screen
![Screenshot_20240208-163044](https://github.com/avluis/Hentoid/assets/44221617/85548d69-55b2-4f8a-a4fe-18872f5a29b7)

**Comment by RobbWatershed** [comment] 2024-02-09 20:06
Duplicate of #623

**Closed by RobbWatershed** 2024-02-09 20:06 UTC
Labels: duplicate
