### ISSUE TITLE
Source:multiporn

### ISSUE THREAD

**Issue by Thewisem** [avluis/Hentoid#842] opened 2021-09-21 23:59 UTC
**Hentoid Version**: 1.15.6

**Device/Android Version**:
Samsung Galaxy Tab A

**Issue details / Repro steps**:
Multiporn is a good website with a huge huge catalogue of books and I am asking for it to be added

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment] 2021-09-22 06:22
Duplicate of #515

**Closed by RobbWatershed** 2021-09-22 06:22 UTC
